## Server Config ##
planx.service.name=ValidatingService-VAL
# Messaging - RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=admin
spring.rabbitmq.username=admin
# Jackson
spring.jackson.default-property-inclusion=NON_NULL
## Logging ##
logging.file.path=logs
logging.file.name=${logging.file.path}/validating-service-val.log
## Custom properties ##
planx.messaging.topic=v1.system-management.validating-service
# main incoming request queue
planx.queues.request.name=${planx.messaging.topic}.val.in
planx.queues.request.key=toolbox.val
# DeadLetterQueue (DLQ)
planx.queues.dlq.name=${planx.messaging.topic}.dlx
planx.queues.dlq.key=failure.message
# Managing Service Error topic
planx.messaging.error.topic=v1.router.managing-service
planx.messaging.error.key=error.message
logging.level.reactor.netty.http.client=INFO
