services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    env_file:
      - mutual.env
    volumes:
      - ../rabbitmq/config:/etc/rabbitmq/
      - planx_rabbitmq_data:/var/lib/rabbitmq/
      - planx_logs:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - planx

  managing-service:
    image: ghcr.io/planx-universe/planx-toolbox/managing:latest
    container_name: managing-service
    env_file:
      - mutual.env
      - managing-service.env
      - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/managing-service/Dockerfile
    volumes:
      - planx_logs:/logs/
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq
    networks:
      - planx

  solving-service-pddl4j:
    image: ghcr.io/planx-universe/planx-toolbox/solving-pddl4j:latest
    container_name: solving-service-pddl4j
    env_file:
      - mutual.env
      - solving-service-pddl4j.env
      - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/solving-service-pddl4j/Dockerfile
    volumes:
      - planx_logs:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  solving-service-pd:
    image: ghcr.io/planx-universe/planx-toolbox/solving-pd:latest
    container_name: solving-service-pd
    env_file:
      - mutual.env
      - solving-service-pd.env
      - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/solving-service-pd/Dockerfile
    volumes:
      - planx_logs:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  parsing-service:
    image: ghcr.io/planx-universe/planx-toolbox/parsing:latest
    container_name: parsing-service
    env_file:
      - mutual.env
      - parsing-service.env
      - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/parsing-service/Dockerfile
    volumes:
      - planx_logs:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  converting-service:
    image: ghcr.io/planx-universe/planx-toolbox/converting:latest
    container_name: converting-service
    env_file:
      - mutual.env
      - converting-service.env
      - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/converting-service/Dockerfile
    volumes:
      - planx_logs:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  frontend-service:
    image: ghcr.io/planx-universe/planx-toolbox/frontend:latest
    container_name: frontend-service
    env_file:
      - mutual.env
    build:
      context: ..
      dockerfile: ./services/frontend-service/Dockerfile
    depends_on:
      - managing-service
    ports:
      - "4200:4200"
    networks:
      - planx

  monitoring-service:
    image: ghcr.io/planx-universe/planx-toolbox/monitoring:latest
    container_name: monitoring-service
    env_file:
      - mutual.env
    build:
      context: ..
      dockerfile: ./services/monitoring-service/Dockerfile
    depends_on:
      - managing-service
    ports:
      - "5000:5000"
    networks:
      - planx

  plan-validation-service:
    image: ghcr.io/planx-universe/planx-toolbox/plan-validation:latest
    container_name: plan-validation-service
    env_file:
     - mutual.env
     - plan-validation-service.env
     - rabbitmq-kotlin.env
    build:
      context: ..
      dockerfile: ./services/plan-validation-service/Dockerfile
    volumes:
      - planx_logs:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

volumes:
  planx_rabbitmq_data:
  planx_logs:

networks:
  planx:
