services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    volumes:
      - ../rabbitmq/config:/etc/rabbitmq/
      - ../rabbitmq/data:/var/lib/rabbitmq/
      - ../logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - planx

  managing-service:
    image: planx.toolbox.router.managing
    container_name: managing-service
    build:
      context: ..
      dockerfile: ./services/managing-service/Dockerfile
    volumes:
      - ../logs/:/logs/
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq
    networks:
      - planx

  solving-service-pddl4j:
    image: planx.toolbox.endpoint.solving:pddl4j
    container_name: solving-service-pddl4j
    build:
      context: ..
      dockerfile: ./services/solving-service-pddl4j/Dockerfile
    volumes:
      - ../logs/:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  solving-service-pd:
    image: planx.toolbox.endpoint.solving:pd
    container_name: solving-service-pd
    build:
      context: ..
      dockerfile: ./services/solving-service-pd/Dockerfile
    volumes:
      - ../logs/:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  parsing-service:
    image: planx.toolbox.transforming.parsing
    container_name: parsing-service
    build:
      context: ..
      dockerfile: ./services/parsing-service/Dockerfile
    volumes:
      - ../logs/:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  converting-service:
    image: planx.toolbox.transforming.converting
    container_name: converting-service
    build:
      context: ..
      dockerfile: ./services/converting-service/Dockerfile
    volumes:
      - ../logs/:/logs/
    depends_on:
      - rabbitmq
    networks:
      - planx

  frontend-service:
    image: planx.toolbox.endpoint.modelling
    container_name: frontend-service
    build:
      context: ..
      dockerfile: ./services/frontend-service/Dockerfile
    depends_on:
      - managing-service
    ports:
      - "4200:4200"
    networks:
      - planx

  monitoring-service:
    image: planx.toolbox.endpoint.monitoring
    container_name: monitoring-service
    build:
      context: ..
      dockerfile: ./services/monitoring-service/Dockerfile
    depends_on:
      - managing-service
    ports:
      - "5000:5000"
    networks:
      - planx

#  plan-validation-service:
#    image: planx.toolbox.system-management.plan-validation
#    container_name: plan-validation-service
#    build:
#      context: ..
#      dockerfile: ./services/plan-validation-service/Dockerfile
#    volumes:
#      - ../logs/:/logs/
#    depends_on:
#      - rabbitmq
#    networks:
#      - planx

networks:
  planx:
